# Generated by Django 4.1.3 on 2022-11-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
