# Generated by Django 4.1.3 on 2022-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_second_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_head_household',
            field=models.BooleanField(default=0, verbose_name='Es cabeza de hogar'),
            preserve_default=False,
        ),
    ]
